services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=${POSTGRES_USER_DEV}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_DEV}
      - POSTGRES_DB=${POSTGRES_DB_DEV}
      - POSTGRES_NON_ROOT_USER=${POSTGRES_NON_ROOT_USER_DEV}
      - POSTGRES_NON_ROOT_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD_DEV}
    volumes:
      - net_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 5432:5432

volumes:
  net_data:
